import { CalendarDays, CreditCard, Search, ShieldCheck, ShipWheel, Store, Waves, Zap } from "lucide-react";

export const featuredYachts = [
  {
    id: "1",
    slug: "loulou-bahr-ahmar",
    name: "لؤلؤة البحر الأحمر",
    location: "بحرنا جدة",
    rating: "4.9",
    reviews: 47,
    capacity: 12,
    price: "يبدأ من 2,500 ريال",
    pricePerHour: 2500,
    type: "LUXURY_YACHT",
    typeLabel: "يخت فاخر",
    length: 18,
    cabins: 3,
    hasAC: true,
    hasWifi: true,
    hasKitchen: true,
    image: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502292239602-b4bfbd46e8c8?auto=format&fit=crop&w=1200&q=80",
    ],
    description: "يخت فاخر مجهز بأحدث المعدات، مثالي للرحلات العائلية والمناسبات الخاصة في البحر الأحمر.",
    store: { name: "يخوت البحر الأحمر", slug: "red-sea-yachts" },
    isFeatured: true,
  },
  {
    id: "2",
    slug: "amwaj-nukhba",
    name: "أمواج النخبة",
    location: "أبحر الشمالية",
    rating: "4.8",
    reviews: 33,
    capacity: 18,
    price: "يبدأ من 3,400 ريال",
    pricePerHour: 3400,
    type: "MOTOR_YACHT",
    typeLabel: "يخت محرك",
    length: 22,
    cabins: 4,
    hasAC: true,
    hasWifi: true,
    hasKitchen: true,
    hasWaterSports: true,
    image: "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1548425087-bff95db55b4e?auto=format&fit=crop&w=1200&q=80",
    ],
    description: "يخت المحرك الفاخر لرحلات لا تُنسى مع عائلتك وأصدقائك على امتداد ساحل جدة.",
    store: { name: "نخبة البحار", slug: "nukhba-bahar" },
    isFeatured: true,
  },
  {
    id: "3",
    slug: "marsa-royal",
    name: "بحرنا رويال",
    location: "ينبع",
    rating: "5.0",
    reviews: 28,
    capacity: 20,
    price: "يبدأ من 4,100 ريال",
    pricePerHour: 4100,
    type: "LUXURY_YACHT",
    typeLabel: "يخت فاخر",
    length: 28,
    cabins: 5,
    hasAC: true,
    hasWifi: true,
    hasKitchen: true,
    hasJetSki: true,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1506719040632-7d586470c936?auto=format&fit=crop&w=1200&q=80",
    ],
    description: "التجربة الملكية الأصيلة في ينبع، يخت مجهز بكل وسائل الراحة والرفاهية.",
    store: { name: "رويال مارينا", slug: "royal-marina" },
    isFeatured: true,
  },
  {
    id: "4",
    slug: "nujum-bahr",
    name: "نجوم البحر",
    location: "بحرنا جدة",
    rating: "4.7",
    reviews: 19,
    capacity: 10,
    price: "يبدأ من 1,800 ريال",
    pricePerHour: 1800,
    type: "SAILING_YACHT",
    typeLabel: "يخت شراعي",
    length: 15,
    cabins: 2,
    hasAC: false,
    hasWifi: true,
    image: "https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?auto=format&fit=crop&w=1200&q=80",
    ],
    description: "رحلة شراعية رومانسية وهادئة مثالية للأزواج والعائلات الصغيرة.",
    store: { name: "يخوت البحر الأحمر", slug: "red-sea-yachts" },
    isFeatured: false,
  },
  {
    id: "5",
    slug: "diamond-sea",
    name: "ماسة البحر",
    location: "أبحر الجنوبية",
    rating: "4.9",
    reviews: 52,
    capacity: 25,
    price: "يبدأ من 5,000 ريال",
    pricePerHour: 5000,
    type: "PARTY_BOAT",
    typeLabel: "قارب حفلات",
    length: 30,
    cabins: 6,
    hasAC: true,
    hasWifi: true,
    hasKitchen: true,
    hasWaterSports: true,
    image: "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?auto=format&fit=crop&w=1200&q=80",
    ],
    description: "قارب الحفلات الأكثر فخامة على ساحل جدة، مثالي للأعياد والمناسبات الكبيرة.",
    store: { name: "نخبة البحار", slug: "nukhba-bahar" },
    isFeatured: true,
  },
  {
    id: "6",
    slug: "speedy-wave",
    name: "الموجة السريعة",
    location: "ينبع",
    rating: "4.6",
    reviews: 14,
    capacity: 8,
    price: "يبدأ من 1,200 ريال",
    pricePerHour: 1200,
    type: "SPEEDBOAT",
    typeLabel: "قارب سريع",
    length: 10,
    cabins: 0,
    hasAC: false,
    hasWifi: false,
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80",
    ],
    description: "للمغامرين الباحثين عن الإثارة والسرعة على أمواج البحر الأحمر.",
    store: { name: "رويال مارينا", slug: "royal-marina" },
    isFeatured: false,
  },
];

export const yachtTypes = [
  { value: "LUXURY_YACHT", label: "يخت فاخر" },
  { value: "MOTOR_YACHT", label: "يخت محرك" },
  { value: "SAILING_YACHT", label: "يخت شراعي" },
  { value: "CATAMARAN", label: "كاتاماران" },
  { value: "SPEEDBOAT", label: "قارب سريع" },
  { value: "PARTY_BOAT", label: "قارب حفلات" },
  { value: "FISHING_BOAT", label: "قارب صيد" },
];

export const cities = ["جدة", "ينبع", "الدمام", "جازان", "الوجه", "القنفذة", "الليث"];

export const mockBookings = [
  {
    id: "b1",
    bookingNumber: "YB-2024-001",
    date: "2026-04-10",
    startTime: "10:00",
    duration: 4,
    numberOfGuests: 8,
    total: 10360,
    status: "CONFIRMED",
    paymentStatus: "PAID",
    customerName: "أحمد محمد العمري",
    customerPhone: "+966501234567",
    yacht: { name: "لؤلؤة البحر الأحمر", slug: "loulou-bahr-ahmar" },
  },
  {
    id: "b2",
    bookingNumber: "YB-2024-002",
    date: "2026-04-12",
    startTime: "14:00",
    duration: 3,
    numberOfGuests: 15,
    total: 14280,
    status: "PENDING",
    paymentStatus: "PENDING",
    customerName: "فيصل السلمي",
    customerPhone: "+966509876543",
    yacht: { name: "أمواج النخبة", slug: "amwaj-nukhba" },
  },
  {
    id: "b3",
    bookingNumber: "YB-2024-003",
    date: "2026-04-08",
    startTime: "09:00",
    duration: 6,
    numberOfGuests: 20,
    total: 29520,
    status: "COMPLETED",
    paymentStatus: "PAID",
    customerName: "خالد الشمري",
    customerPhone: "+966505555555",
    yacht: { name: "بحرنا رويال", slug: "marsa-royal" },
  },
  {
    id: "b4",
    bookingNumber: "YB-2024-004",
    date: "2026-04-15",
    startTime: "16:00",
    duration: 2,
    numberOfGuests: 6,
    total: 4140,
    status: "PENDING",
    paymentStatus: "PENDING",
    customerName: "نورة العتيبي",
    customerPhone: "+966507777777",
    yacht: { name: "لؤلؤة البحر الأحمر", slug: "loulou-bahr-ahmar" },
  },
  {
    id: "b5",
    bookingNumber: "YB-2024-005",
    date: "2026-04-06",
    startTime: "11:00",
    duration: 5,
    numberOfGuests: 10,
    total: 20700,
    status: "CANCELLED",
    paymentStatus: "REFUNDED",
    customerName: "عبدالله القحطاني",
    customerPhone: "+966502222222",
    yacht: { name: "ماسة البحر", slug: "diamond-sea" },
  },
];

export const mockStores = [
  {
    id: "s1",
    slug: "red-sea-yachts",
    name: "يخوت البحر الأحمر",
    city: "جدة",
    owner: "محمد الأحمد",
    status: "ACTIVE",
    totalBookings: 124,
    totalRevenue: 387600,
    averageRating: 4.8,
    yachts: 4,
    commissionRate: 12,
  },
  {
    id: "s2",
    slug: "nukhba-bahar",
    name: "نخبة البحار",
    city: "جدة",
    owner: "عبدالرحمن السيف",
    status: "ACTIVE",
    totalBookings: 98,
    totalRevenue: 312400,
    averageRating: 4.9,
    yachts: 3,
    commissionRate: 10,
  },
  {
    id: "s3",
    slug: "royal-marina",
    name: "رويال مارينا",
    city: "ينبع",
    owner: "طارق الزهراني",
    status: "ACTIVE",
    totalBookings: 56,
    totalRevenue: 218900,
    averageRating: 4.7,
    yachts: 2,
    commissionRate: 12,
  },
  {
    id: "s4",
    slug: "eastern-yachts",
    name: "يخوت الشرقية",
    city: "الدمام",
    owner: "وليد العسيري",
    status: "UNDER_REVIEW",
    totalBookings: 0,
    totalRevenue: 0,
    averageRating: null,
    yachts: 1,
    commissionRate: 15,
  },
];

export const mockAdminStats = {
  totalUsers: 412,
  totalStores: 4,
  totalYachts: 10,
  totalBookings: 278,
  totalRevenue: 918900,
  totalCommissions: 110268,
  pendingBookings: 23,
  activeYachts: 8,
};

export const steps = [
  {
    title: "استكشف اليخت المناسب",
    description: "فلترة ذكية حسب المدينة والسعة والسعر والتاريخ حتى يصل العميل للخيار الأنسب بسرعة.",
    icon: Search,
  },
  {
    title: "تحقق من التوافر",
    description: "تقويم واضح مع المواعيد المحجوزة والمتاحة لتقليل التواصل اليدوي ورفع معدل الإغلاق.",
    icon: CalendarDays,
  },
  {
    title: "ادفع بثقة",
    description: "بوابة دفع موثوقة تناسب السوق السعودي وتمنح الطرفين تأكيدًا فوريًا للحجز.",
    icon: CreditCard,
  },
  {
    title: "انطلق برحلتك",
    description: "إشعارات وتأكيدات ووثائق أساسية تجعل التجربة أكثر احترافية من المراسلات المتفرقة.",
    icon: ShipWheel,
  },
];

export const highlights = [
  {
    title: "سوق متخصص بالكامل",
    description: "تركيز كامل على اليخوت والرحلات البحرية بدلًا من قوائم عامة ضعيفة التحويل.",
    icon: Waves,
  },
  {
    title: "متجر مستقل لكل مشغل",
    description: "بنية مناسبة لتعدد المتاجر مع تخصيص الهوية والعمولة والبيانات التشغيلية.",
    icon: Store,
  },
  {
    title: "ثقة ومدفوعات آمنة",
    description: "أساس مناسب لدمج Moyasar في MVP ثم إضافة مزيد من مزودي الدفع لاحقًا.",
    icon: ShieldCheck,
  },
  {
    title: "قابلية توسع واضحة",
    description: "الهيكل الحالي يهيئنا لإضافة التحليلات والمراجعات والتنبيهات دون إعادة بناء جذرية.",
    icon: Zap,
  },
];
